version: '3.7'

services:
  sfcastapiplatformcustom_api_php_fpm:
    container_name: sfcastapiplatformcustom-api-php-fpm
    build: docker/php-fpm
    ports:
      - "8700:9001"
    volumes:
      - .:/var/www/sfcastapiplatformcustom
    depends_on:
      - sfcastapiplatformcustom_api_db
    environment:
      PHP_IDE_CONFIG: serverName=sfcastapiplatformcustom
      XDEBUG_CONFIG: remote_port=9999
      PHP_CS_FIXER_IGNORE_ENV: 1

  sfcastapiplatformcustom_api_http:
    container_name: sfcastapiplatformcustom-api-http
    image: nginx:1.19.1
    ports:
      - "8710:80"
    depends_on:
      - sfcastapiplatformcustom_api_php_fpm
    volumes:
      - .:/var/www/sfcastapiplatformcustom
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf

  sfcastapiplatformcustom_api_db:
    container_name: sfcastapiplatformcustom-api-db
    image: postgres:12
    ports:
      - "8720:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: sfcastapiplatformcustom
      POSTGRES_DB: sfcastapiplatformcustom
      POSTGRES_USER: sfcastapiplatformcustom
